Calculate engagement & repeat uids per episode
AfricasVoices/Project-ICRAF pull request #32
Opened 2019-05-22 09:32 UTC by IsaackMwenda

2019-05-22 10:01 UTC, as2388 requested changes

2019-05-22 10:01 UTC, as2388 commented on pipeline.py
> +     engagement = Engagement.generate(data, phone_number_uuid_table)
If you're not doing anything with `engagement` then no need to store it

2019-05-22 10:01 UTC, as2388 commented on src/engagement.py
> +    def generate(data, phone_number_uuid_table):
```suggestion
    def compute_statistics(data, phone_number_uuid_table):
```
perhaps? (You're not actually generating engagement here :P)

2019-05-22 10:01 UTC, as2388 commented on src/engagement.py
> +        prints out engagements numbers per Episode
```suggestion
        Prints out engagements numbers for each episode
        
```

2019-05-22 10:01 UTC, as2388 commented on src/engagement.py
> +        :return: data
If you're not modifying the data don't return it.

2019-05-22 10:01 UTC, as2388 commented on src/engagement.py
> +                        s01e02_uids.add(phone_number_uuid_table.get_phone(td['uid']))
Why do you need to use phone numbers rather than uuids?

2019-05-22 10:01 UTC, as2388 commented on src/engagement.py
> +                        s01e02_uids.add(phone_number_uuid_table.get_phone(td['uid']))
If you're using a phone number this would need to be called s01e02_phone_numbers. But please don't unless there's a compelling reason why uuids don't suffice here

2019-05-22 10:01 UTC, as2388 commented on src/engagement.py
> +                if plan.raw_field == "rqa_s01e01_raw":
There is a huge amount of duplicated code here (or if it's different, it's really not obvious where). Can you reduce this e.g. by iterating over all the raw fields in PipelineConfiguration.RQA_CODING_PLANS and storing in a dict of sets?

2020-06-16 11:54 UTC, IsaackMwenda commented
PR outdated - Closing

2020-06-16 11:55 UTC, closed without merging